### ISSUE TITLE
Hubot needs a restart on Heroku a couple times per day

### ISSUE THREAD

**Issue by tanookiben** [slackhq/hubot-slack#146]
I'm not quite sure what's causing Hubot to die a couple times per day. The logs don't indicate anything is particularly broken (line two with `app[web.1]` is the last line in the logs before I do `heroku restart`):

```
2015-01-30T00:01:56.233852+00:00 heroku[router]: at=info method=POST path="/heroku/keepalive" host=benspotatoes-hubot.herokuapp.com request_id=19200fc6-454e-412d-8b30-470be362aea9 fwd="54.144.91.194" dyno=web.1 connect=34ms service=44ms status=200 bytes=165
2015-01-30T00:01:56.230683+00:00 app[web.1]: [Fri Jan 30 2015 00:01:56 GMT+0000 (UTC)] INFO keepalive pong: 200 OK
2015-01-30T00:03:17.688848+00:00 heroku[web.1]: State changed from up to starting
2015-01-30T00:03:20.448443+00:00 heroku[web.1]: Starting process with command `bin/hubot -a slack -n potato -l .`
2015-01-30T00:03:20.777794+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-01-30T00:03:22.567125+00:00 heroku[web.1]: Process exited with status 0
2015-01-30T00:03:23.574064+00:00 app[web.1]: Fri, 30 Jan 2015 00:03:23 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
2015-01-30T00:03:23.574088+00:00 app[web.1]: Fri, 30 Jan 2015 00:03:23 GMT connect deprecated limit: Restrict request size at location of read at node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
2015-01-30T00:03:23.578407+00:00 app[web.1]: [Fri Jan 30 2015 00:03:23 GMT+0000 (UTC)] DEBUG Loading adapter slack
2015-01-30T00:03:24.000204+00:00 app[web.1]: [Fri Jan 30 2015 00:03:23 GMT+0000 (UTC)] INFO Connecting...
2015-01-30T00:03:24.438001+00:00 heroku[web.1]: State changed from starting to up
...
```

Not quite sure if this something broken with my implementation or if Heroku changed the effect of the `HEROKU_URL` config. This is a relatively new problem, probably less than 2-3 weeks old. Prior to upgrading to v3 I don't think I've ever run into this issue.

**Comment by evansolomon** [comment]
The adapter doesn't do anything special for heroku.  It sounds like you may be using [hubot-heroku-keepalive](https://github.com/hubot-scripts/hubot-heroku-keepalive) or the (I think now legacy) heroku keepalive behavior in core hubot.  Maybe when you updated this adapter some of your other dependencies changed?

**Comment by tanookiben** [comment]
Ah, didn't know there was a new way to keep hubot alive, will dig into `hubot-heroku-keepalive` and see if I can get it to work. Thanks!
