### ISSUE TITLE
update to node 0.12 hubot will no longer start

### ISSUE THREAD

**Issue by khera** [slackhq/hubot-slack#155]
Today I updated node from 0.10.35 to 0.12.0. Restart of the hubot results in the following error. I did a manual ```npm update``` in the hubot home directory, and it rebuilt a lot of stuff. I also did a force reinstall of the slack integration using ```npm install hubot-slack --save``` yet the error persists.

Running Node 0.12.0, npm 2.2.0, hubot-slack updated to latest release. All on FreeBSD 10.1.

```
2015-02-12 15:53:40.551898500 Thu, 12 Feb 2015 20:53:40 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
2015-02-12 15:53:40.552746500 Thu, 12 Feb 2015 20:53:40 GMT connect deprecated limit: Restrict request size at location of read at node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
2015-02-12 15:53:40.703328500 [Thu Feb 12 2015 15:53:40 GMT-0500 (EST)] INFO Connecting...
2015-02-12 15:53:40.722137500 [Thu Feb 12 2015 15:53:40 GMT-0500 (EST)] ERROR Received error EAI_BADFLAGS
2015-02-12 15:53:40.722590500 [Thu Feb 12 2015 15:53:40 GMT-0500 (EST)] ERROR undefined
2015-02-12 15:53:40.722630500 [Thu Feb 12 2015 15:53:40 GMT-0500 (EST)] ERROR Exiting in 1 second
2015-02-12 15:53:40.724862500 [Thu Feb 12 2015 15:53:40 GMT-0500 (EST)] ERROR TypeError: Cannot read property 'close' of null
2015-02-12 15:53:40.724863500   at Client.reconnect (/u/lorax1/home/hubot/hal/node_modules/hubot-slack/node_modules/slack-client/src/client.js:187:12)
2015-02-12 15:53:40.724864500   at Client._onLogin (/u/lorax1/home/hubot/hal/node_modules/hubot-slack/node_modules/slack-client/src/client.js:77:23)
2015-02-12 15:53:40.724866500   at /u/lorax1/home/hubot/hal/node_modules/hubot-slack/node_modules/slack-client/src/client.js:2:59
2015-02-12 15:53:40.724871500   at ClientRequest.<anonymous> (/u/lorax1/home/hubot/hal/node_modules/hubot-slack/node_modules/slack-client/src/client.js:638:18)
2015-02-12 15:53:40.724872500   at ClientRequest.emit (events.js:107:17)
2015-02-12 15:53:40.724873500   at TLSSocket.socketErrorListener (_http_client.js:272:9)
2015-02-12 15:53:40.724874500   at TLSSocket.emit (events.js:129:20)
2015-02-12 15:53:40.724874500   at net.js:923:16
2015-02-12 15:53:40.724877500   at process._tickCallback (node.js:355:11)
2015-02-12 15:53:40.724877500
```

**Comment by khera** [comment]
Seems to be a known issue with Node: https://github.com/joyent/node/issues/8540

**Comment by evansolomon** [comment]
From the discussion on joyent/node it sounds like this is a Node core and/or FreeBSD bug, so I'm guessing we can't do much about it here.

Does that sound right?  If so, it's probably best to close this issue since it's really just a symptom of the other one(s).

Let me know if I'm missing anything though.

**Comment by khera** [comment]
I agree with your assessment. For now I backed down to node 0.10.
