### ISSUE TITLE
App crashing on startup w/ Heroku

### ISSUE THREAD

**Issue by Logikz** [slackhq/hubot-slack#160]
Hi,
I'm learning how to set up Hubot with Slack, so I went through the steps to get it working on Heroku.  I'm unfamiliar with all the new tools so not sure where the problem lies, if this is not the right place for this  then I will look elsewhere. 

On startup my app is crashing after it connects to Slack.  I have a few scripts I want to run with hubot and slack, but I don't have those included yet.

Here is the heroku log:
```
2015-02-27T23:14:44.371587+00:00 heroku[web.1]: Starting process with command `b
in/hubot --adapter slack`
2015-02-27T23:14:45.191441+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-02-27T23:14:45.191422+00:00 app[web.1]: Detected 512 MB available memory, 5
12 MB limit per process (WEB_MEMORY)
2015-02-27T23:14:47.074600+00:00 app[web.1]: Fri, 27 Feb 2015 23:14:47 GMT conne
ct deprecated limit: Restrict request size at location of read at node_modules/h
ubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15

2015-02-27T23:14:47.074058+00:00 app[web.1]: Fri, 27 Feb 2015 23:14:47 GMT conne
ct deprecated multipart: use parser (multiparty, busboy, formidable) npm module
instead at node_modules/hubot/node_modules/express/node_modules/connect/lib/midd
leware/bodyParser.js:56:20
2015-02-27T23:14:47.277398+00:00 app[web.1]: [Fri Feb 27 2015 23:14:47 GMT+0000
(UTC)] INFO Connecting...
2015-02-27T23:14:47.402780+00:00 app[web.1]: [Fri Feb 27 2015 23:14:47 GMT+0000
(UTC)] INFO Logged in as jarvis of OC Ingress, but not yet connected
2015-02-27T23:14:47.586467+00:00 heroku[web.1]: State changed from starting to u
p
2015-02-27T23:14:48.237427+00:00 app[web.1]: [Fri Feb 27 2015 23:14:48 GMT+0000
(UTC)] ERROR Error loading scripts from npm package - TypeError: object is not a
 function
2015-02-27T23:14:48.237433+00:00 app[web.1]:   at Robot.loadExternalScripts (/ap
p/node_modules/hubot/src/robot.coffee:263:11, <js>:212:39)
2015-02-27T23:14:48.237437+00:00 app[web.1]:   at fs.js:272:14
2015-02-27T23:14:48.237439+00:00 app[web.1]:   at Object.oncomplete (fs.js:108:1
5)
2015-02-27T23:14:48.237440+00:00 app[web.1]:
2015-02-27T23:14:48.237435+00:00 app[web.1]:   at /app/node_modules/hubot/bin/hu
bot:119:11, <js>:123:26
2015-02-27T23:14:48.112868+00:00 app[web.1]: [Fri Feb 27 2015 23:14:48 GMT+0000
(UTC)] INFO Slack client now connected
2015-02-27T23:14:48.881541+00:00 heroku[web.1]: Process exited with status 1
2015-02-27T23:14:48.902547+00:00 heroku[web.1]: State changed from up to crashed
```

Any guidance would be appreciative.

**Comment by evansolomon** [comment]
> Error loading scripts from npm package

Sounds like the problem is in some external scripts loaded from npm.  Can you remove the npm scripts and see if it still crashes?

**Comment by Logikz** [comment]
Here's my list of external scripts, do you want me to remove all of them?
[
  "hubot-diagnostics",
  "hubot-help",
  "hubot-heroku-keepalive",
  "hubot-google-images",
  "hubot-google-translate",
  "hubot-pugme",
  "hubot-maps",
  "hubot-redis-brain",
  "hubot-rules",
  "hubot-shipit",
  "hubot-youtube",
  "hubot-slack"
]

**Comment by Logikz** [comment]
I removed every script except for hubot-slack and get the same error

**Comment by evansolomon** [comment]
hubot-slack shouldn't be in that list (it is an adapter, not a script).

**Comment by Logikz** [comment]
oh, that's probably the problem, not sure why I added that... let me verify

**Comment by Logikz** [comment]
cool, that was it. thanks!

**Comment by evansolomon** [comment]
:+1:
