### ISSUE TITLE
npm install hubot-slack --save fails

### ISSUE THREAD

**Issue by pklapperich** [slackhq/hubot-slack#199]
Following the install steps in README.md

$ npm install hubot-slack --save
\-
\> ws@0.4.31 install /home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws
\> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:89: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/build'
hubot-slack@3.3.0 node_modules/hubot-slack
└── slack-client@1.4.1 (log@1.4.0, coffee-script@1.9.3, ws@0.4.31)

**Comment by SamHam** [comment]
Same issue here

**Comment by pklapperich** [comment]
npm install hubot-slack --save still fails to build for me. But I was able to get hubot-slack working without that step. Here's what I did:

1. git clone https://github.com/slackhq/hubot-slack/
2. npm install -g hubot coffee-script yo generator-hubot
3. cd hubot-slack
4. yo hubot        (enter without quotes "slack" for the adapter; replace any files it asks you to)
5. Edit external-scripts.json and add "hubot-ingress" to the list (commas where appropriate)

At this point, you should be able to Test your bot locally as shown in README.md

To deploy to heroku, 

6. Edit hubot-slack/.gitignore and REMOVE the line "node_modules"
7. use git add and git commit to add any folders in node_modules that you have enabled in external_scripts.json
7. Follow the instructions for deploying to Heroku listed in the README.md.

**Comment by technicalpickles** [comment]
What version of node and npm are you using? You can get this with `node --version` and `npm --version`.

**Comment by technicalpickles** [comment]
```
make: Entering directory '/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/build'
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:89: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/build'
```

Based on this, the failing package is https://github.com/websockets/ws which is a dependency of https://github.com/slackhq/node-slack-client

**Comment by pklapperich** [comment]
$ node --version
v0.12.4
$ npm --version
2.11.1

**Comment by pklapperich** [comment]
I'm able to 'npm install ws' without problems. Following with npm install hubot-slack still fails. I wonder why ns installs on its own but not as s hubot-slack dependency.

Below is my full ./node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/builderror.log

````
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘void NanThrowError(const char*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:209:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
       ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:213:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:209:30: error: ‘New’ is not a member of ‘v8::String’
       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
                              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:213:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘void NanThrowError(v8::Handle<v8::Value>)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:218:5: error: ‘ThrowException’ is not a member of ‘v8’
     v8::ThrowException(error);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘void NanThrowError(const char*, int)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:222:53: error: ‘New’ is not a member of ‘v8::String’
     v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:224:14: error: ‘New’ is not a member of ‘v8::String’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:224:65: error: no matching function for call to ‘v8::Int32::New(const int&)’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                                                 ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘void NanThrowTypeError(const char*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:209:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
       ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:229:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:209:30: error: ‘New’ is not a member of ‘v8::String’
       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
                              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:229:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘void NanThrowRangeError(const char*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:209:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
       ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:233:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:209:30: error: ‘New’ is not a member of ‘v8::String’
       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
                              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:233:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback(const v8::Local<v8::Function>&)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:450:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Local<v8::Object> obj = v8::Object::New();
                                                 ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:2388:24: note: candidate: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:103:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:451:14: note: in expansion of macro ‘NanSymbol’
     obj->Set(NanSymbol("callback"), fn);
              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In destructor ‘NanCallback::~NanCallback()’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:457:12: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Dispose’
     handle.Dispose();
            ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:458:12: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
            ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In member function ‘v8::Local<v8::Function> NanCallback::GetFunction()’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:103:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:462:46: note: in expansion of macro ‘NanSymbol’
     return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:463:25: error: expected primary-expression before ‘>’ token
         .As<v8::Function>();
                         ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:463:27: error: expected primary-expression before ‘)’ token
         .As<v8::Function>();
                           ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In member function ‘void NanCallback::Call(int, v8::Local<v8::Value>*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:103:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:475:12: note: in expansion of macro ‘NanSymbol’
        Get(NanSymbol("callback")).As<v8::Function>();
            ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:475:50: error: expected primary-expression before ‘>’ token
        Get(NanSymbol("callback")).As<v8::Function>();
                                                  ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:475:52: error: expected primary-expression before ‘)’ token
        Get(NanSymbol("callback")).As<v8::Function>();
                                                    ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:477:20: error: ‘GetCurrent’ is not a member of ‘v8::Context’
     callback->Call(v8::Context::GetCurrent()->Global(), argc, argv);
                    ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: At global scope:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:518:3: error: ‘uv_work_t’ does not name a type
   uv_work_t request;
   ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In constructor ‘NanAsyncWorker::NanAsyncWorker(NanCallback*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:490:5: error: ‘request’ was not declared in this scope
     request.data = this;
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In member function ‘void NanAsyncWorker::SavePersistent(const char*, v8::Local<v8::Object>&)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:103:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:529:17: note: in expansion of macro ‘NanSymbol’
     handle->Set(NanSymbol(key), obj);
                 ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In member function ‘v8::Local<v8::Object> NanAsyncWorker::GetFromPersistent(const char*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:103:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:536:24: note: in expansion of macro ‘NanSymbol’
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                        ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:536:53: error: expected primary-expression before ‘>’ token
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                                                     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:536:55: error: expected primary-expression before ‘)’ token
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                                                       ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In member function ‘virtual void NanAsyncWorker::HandleErrorCallback()’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:549:30: error: ‘New’ is not a member of ‘v8::String’
         v8::Exception::Error(v8::String::New(errmsg))
                              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: At global scope:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:555:30: error: variable or field ‘NanAsyncExecute’ declared void
 inline void NanAsyncExecute (uv_work_t* req) {
                              ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:555:30: error: ‘uv_work_t’ was not declared in this scope
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:555:41: error: ‘req’ was not declared in this scope
 inline void NanAsyncExecute (uv_work_t* req) {
                                         ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:560:38: error: variable or field ‘NanAsyncExecuteComplete’ declared void
 inline void NanAsyncExecuteComplete (uv_work_t* req) {
                                      ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:560:38: error: ‘uv_work_t’ was not declared in this scope
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:560:49: error: ‘req’ was not declared in this scope
 inline void NanAsyncExecuteComplete (uv_work_t* req) {
                                                 ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘void NanAsyncQueueWorker(NanAsyncWorker*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:568:23: error: ‘uv_default_loop’ was not declared in this scope
       uv_default_loop()
                       ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:569:16: error: ‘class NanAsyncWorker’ has no member named ‘request’
     , &worker->request
                ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:570:7: error: ‘NanAsyncExecute’ was not declared in this scope
     , NanAsyncExecute
       ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:571:8: error: ‘uv_after_work_cb’ was not declared in this scope
     , (uv_after_work_cb)NanAsyncExecuteComplete
        ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:572:3: error: ‘uv_queue_work’ was not declared in this scope
   );
   ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:716:78: error: no matching function for call to ‘v8::Local<v8::String>::New(v8::Handle<v8::String>)’
   v8::Local<v8::String> str = v8::Local<v8::String>::New(val.As<v8::String>());
                                                                              ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:368:29: note: candidate: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, v8::Handle<T>) [with T = v8::String]
   V8_INLINE static Local<T> New(Isolate* isolate, Handle<T> that);
                             ^
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:368:29: note:   candidate expects 2 arguments, 1 provided
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:369:29: note: candidate: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, const v8::PersistentBase<T>&) [with T = v8::String]
   V8_INLINE static Local<T> New(Isolate* isolate,
                             ^
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:369:29: note:   candidate expects 2 arguments, 1 provided
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:391:29: note: candidate: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, T*) [with T = v8::String]
   V8_INLINE static Local<T> New(Isolate* isolate, T* that);
                             ^
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:391:29: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In function ‘char* NanFromV8String(v8::Handle<v8::Value>, Nan::Encoding, size_t*, char*, size_t, int)’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:769:3: error: ‘AsciiValue’ is not a member of ‘v8::String’
   v8::String::AsciiValue value(toStr);
   ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:832:39: error: ‘value’ was not declared in this scope
       sz_ = _nan_base64_decoded_size(*value, toStr->Length());
                                       ^
../src/bufferutil.cc: In static member function ‘static void BufferUtil::Initialize(v8::Handle<v8::Object>)’:
../src/bufferutil.cc:27:58: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
     Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                          ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../src/bufferutil.cc:32:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("BufferUtil"), t->GetFunction());
                 ^
In file included from ../src/bufferutil.cc:15:0:
../src/bufferutil.cc: In static member function ‘static void BufferUtil::Merge(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/bufferutil.cc:60:25: error: too few arguments to function ‘v8::Handle<v8::Boolean> v8::True(v8::Isolate*)’
     NanReturnValue(True());
                         ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:195:65: note: in definition of macro ‘NanReturnValue’
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                 ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:6613:17: note: declared here
 Handle<Boolean> True(Isolate* isolate) {
                 ^
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:195:70: error: return-statement with a value, in function returning 'void' [-fpermissive]
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                      ^
../src/bufferutil.cc:60:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(True());
     ^
../src/bufferutil.cc: In static member function ‘static void BufferUtil::Unmask(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/bufferutil.cc:81:25: error: too few arguments to function ‘v8::Handle<v8::Boolean> v8::True(v8::Isolate*)’
     NanReturnValue(True());
                         ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:195:65: note: in definition of macro ‘NanReturnValue’
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                 ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:6613:17: note: declared here
 Handle<Boolean> True(Isolate* isolate) {
                 ^
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:195:70: error: return-statement with a value, in function returning 'void' [-fpermissive]
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                      ^
../src/bufferutil.cc:81:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(True());
     ^
../src/bufferutil.cc: In static member function ‘static void BufferUtil::Mask(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/bufferutil.cc:106:25: error: too few arguments to function ‘v8::Handle<v8::Boolean> v8::True(v8::Isolate*)’
     NanReturnValue(True());
                         ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:195:65: note: in definition of macro ‘NanReturnValue’
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                 ^
In file included from ../src/bufferutil.cc:7:0:
/home/pklapperich/.node-gyp/0.12.4/deps/v8/include/v8.h:6613:17: note: declared here
 Handle<Boolean> True(Isolate* isolate) {
                 ^
In file included from ../src/bufferutil.cc:15:0:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:195:70: error: return-statement with a value, in function returning 'void' [-fpermissive]
 # define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                      ^
../src/bufferutil.cc:106:5: note: in expansion of macro ‘NanReturnValue’
     NanReturnValue(True());
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h: In instantiation of ‘void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:498:34:   required from here
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:237:5: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Dispose’
     handle.Dispose(nan_isolate);
     ^
/home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/node_modules/nan/nan.h:238:5: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
     ^
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.4-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pklapperich/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
````

**Comment by technicalpickles** [comment]
@pklapperich npm bundles a dependency's dependencies separate from each other, with the exact version depended on, so hubot-slack can depend on slack-client to have it's own ws. When you `npm install slack-client ws`, that's installing the latest, rather than whatever the dependency specified.

I think that's a good case for updating slack-client's ws to a newer version, and hubot-slack to the latest slack-client after that.

**Comment by EnzanNoMetsuke** [comment]
Hi all. I believe I'm having the same problem. @technicalpickles: I tried your recommendation of updating slack-client's ws and started by taking it to 0.4.32. I bumped the dependency in package.json and then ran `npm install` from the package's directory:
```
paul@devbox:~/Workspace/hal/node_modules/hubot-slack/node_modules/slack-client$ npm install
npm WARN package.json slack-client@1.4.1 No license field.

> ws@0.4.32 install /home/paul/Workspace/hal/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/paul/Workspace/hal/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/home/paul/Workspace/hal/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/build'
/
> slack-client@1.4.1 prepublish /home/paul/Workspace/hal/node_modules/hubot-slack/node_modules/slack-client
> grunt prepublish

sh: 1: grunt: not found

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/paul/.nvm/versions/node/v0.12.4/bin/node" "/home/paul/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! slack-client@1.4.1 prepublish: `grunt prepublish`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the slack-client@1.4.1 prepublish script 'grunt prepublish'.
```

**Comment by jachin84** [comment]
I've also got the exact same problem. I have Visual Studio 2013 and Python27 installed.

**Comment by jachin84** [comment]
Any idea on how to fix this? Would love to get this working on Windows.

**Comment by superboum** [comment]
Only solution found to fix it : 

```bash
nvm use v0.10.32
npm install
```

It seems that ws is not compatible with Node.js v0.12.4...

**Comment by DEGoodmanWilson** [comment]
I'm going to speculate that this will be fixed with https://github.com/slackhq/hubot-slack/pull/309 so I am closing unless I'm proven wrong!
