### ISSUE TITLE
Unable to send hubot response to channel (Object #<Object> has no method 'replace')

### ISSUE THREAD

**Issue by absyah** [slackhq/hubot-slack#253]
It is first time i'm using hubot, with slack.
So basically I want to send the hubot response to slack with the following code : 

```
robot.send {room: "news-room"}, "Some message"
```
But I got following error on heroku log : 

```
2015-11-18T06:36:02.362782+00:00 app[web.1]: [Wed Nov 18 2015 06:36:02 GMT+0000 (UTC)] ERROR TypeError: Object #<Object> has no method 'replace'
2015-11-18T06:36:02.362786+00:00 app[web.1]:   at SlackBot.send (/app/node_modules/hubot-slack/src/slack.coffee:229:47, <js>:278:19)
2015-11-18T06:36:02.362787+00:00 app[web.1]:   at runAdapterSend (/app/node_modules/hubot/src/response.coffee:82:34, <js>:87:50)
2015-11-18T06:36:02.362788+00:00 app[web.1]:   at allDone (/app/node_modules/hubot/src/middleware.coffee:41:37, <js>:32:16)
2015-11-18T06:36:02.362788+00:00 app[web.1]:   at /app/node_modules/hubot/node_modules/async/lib/async.js:274:13
2015-11-18T06:36:02.362789+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/hubot/node_modules/async/lib/async.js:142:20)
2015-11-18T06:36:02.362790+00:00 app[web.1]:   at Object.async.reduce (/app/node_modules/hubot/node_modules/async/lib/async.js:268:15)
2015-11-18T06:36:02.362790+00:00 app[web.1]:   at /app/node_modules/hubot/src/middleware.coffee:46:7, <js>:35:22
2015-11-18T06:36:02.362791+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)

```
It seems `{room: "news-room"}` considered as part of message.

Any clue how to solve this? 

Thanks in advance :bow: 

EDITED : 
i'm using `"hubot-slack": "^3.4.2"`

**Comment by evansolomon** [comment]
If you want to respond to an message (I think this is what your title is describing) then something like this is what you want.

```coffee
module.exports = (robot) ->
  robot.respond 'whatever', (msg) -> msg.send 'This is my response message'
```

If you want to send a message to a specific channel (this seems like what your code is attempting to do) then something like this should work.

```coffee
module.exports = (robot) ->
  doSomeStuffToDecideIfAndWhenToSendThisThing ->
    robot.messageRoom 'news-room', 'Some message'
```

**Comment by absyah** [comment]
@evansolomon Thanks it works.
I could not see `messageRoom` in the doc and test :pensive: 

Thank you very much, I close this :bow:

**Comment by evansolomon** [comment]
No problem. Fyi the main hubot docs might be a helpful thing to check out, in case you haven't found those yet: https://hubot.github.com/docs/scripting/

**Comment by absyah** [comment]
Thanks for the link :bow:
