### ISSUE TITLE
Not sending message when define envelope.room on Send method

### ISSUE THREAD

**Issue by jtomaszon** [slackhq/hubot-slack#274]
Hey guys,  I'm trying to forward ANY coming from multiples channel just to ONE specific.
```  
  robot.hear(/[.]*/i, function (res) {
    var message = res.envelope,
        room = message.room;

    res.send({'room': '#forwarding-messages'}, 'foobar');
    robot.logger.info('someone is look for us on: ', room);

  });
```

And I'm receiving this error:
```
[Wed Feb 10 2016 12:18:25 GMT+0000 (UTC)] ERROR TypeError: msg.replace is not a function
  at SlackBot.send (/home/ubuntu/hubot/awaybot/node_modules/hubot-slack/src/slack.coffee:229:47, <js>:278:19)
  at runAdapterSend (/home/ubuntu/hubot/awaybot/node_modules/hubot/src/response.coffee:82:34, <js>:87:50)
  at allDone (/home/ubuntu/hubot/awaybot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/ubuntu/hubot/awaybot/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/ubuntu/hubot/awaybot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/ubuntu/hubot/awaybot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /home/ubuntu/hubot/awaybot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at doNTCallback0 (node.js:419:9)
  at process._tickCallback (node.js:348:13)
```

If I don't send the envelop object, everything works OK.
Any ideas?

**Comment by jtomaszon** [comment]
Seems that the message using a non existent user is breaking the msg.replace.
For example, sending a message with "@non_existent_user" will break it

**Comment by cheif** [comment]
I got this error when trying to send an error-object as well, I suppose this might be because an error-object has a message-property. It was fixed by using `msg.send err.toString()` instead. FYI
