### ISSUE TITLE
Can't set topic of private room

### ISSUE THREAD

**Issue by Ajnasz** [slackhq/hubot-slack#350]
#### Description
Calling `msg.topic` on message from a private room throws an exception.

#### Steps to reproduce:

1. Start hubot with the following script: https://gist.github.com/Ajnasz/f63be5047b84d5104dd6d8e16f81deb9
2. Invite the bot into a private room
3. type set topic in the room

### Expected result:
Set the topic of the room

### Actual result:
Topic not set, see error in the logs.

### Attachments:
```

Unhandled rejection SlackAPIError: channel_not_found
  at makeAPICallPromiseResolverInner (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/client.js:156:22)
  at handleHttpResponse (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/call-transport.js:105:5)
  at handleTransportResponse (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/call-transport.js:142:19)
  at apply (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:484:17)
  at wrapper (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:5156:16)
  at Request.handleRequestTranportRes (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
  at apply (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:484:17)
  at Request.wrapper [as _callback] (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:5156:16)
  at Request.self.callback (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/request/request.js:187:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/request/request.js:1044:10)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (/foo/src/stuart/node_modules/hubot-slack/node_modules/@slack/client/node_modules/request/request.js:965:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:921:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
```

**Comment by DEGoodmanWilson** [comment]
Just to check, this is in v4?

**Comment by Ajnasz** [comment]
Yes, it's working in 3, but I tried to upgrade to 4, and my script didn't
work.

Don Goodman-Wilson <notifications@github.com> ezt írta (időpont: 2016. aug.
25., Cs 8:17):

**Comment by DEGoodmanWilson** [comment]
I do believe this is all done now ;)
